name: "udpxy"
version: "2.0.0"
slug: "udpxy"
description: >-
  Udp Proxy
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
url: "https://github.com/dreyercito/addon-udpxy/"
host_network: true
options:
  port: 5056
schema:
  port: int



