name: "udpxy"
version: "2.0.1"
slug: "udpxy"
description: >-
  Udp Proxy
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
url: "https://github.com/dreyercito/addon-udpxy/"
host_network: true
init: false
startup: application
options:
  port: 5056
  interface: "end0"
schema:
  port: int
  interface: str



